config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resources :book_comments,only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
    resources :messages,only: [:create]
    resources :rooms,only: [:create,:show]
    resources :groups,only: [:new,:create,:index,:show,:edit,:update]do
    resource :group_users,only: [:create,:destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
    end
    get "search"=>"searches#search"




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :read_counts,dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

   def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

   def self.looks(search,word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book= Book.where("title LIKE?","#{word}%")
      elsif search == "backward_match"
        @book = Book.where("title LIKE?","%#{word}")
        elsif search == "partial_match"
          @book = Book.where("title LIKE?","%#{word}%")
        else
          @book = Book.all
        end
      end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment,presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users,dependent: :destroy
  belongs_to :owner,class_name: "User"
  has_many :users,through: :group_users,source: :user


  validates :name,presence: true
  validates :introduction,presence: true

  has_one_attached :group_image

  def is_owned_by?(user)
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :message,presence: true,length: {maximum: 140}
end

app/models/read_count.rb
class ReadCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
 belongs_to :follower, class_name:"User"
 belongs_to :followed, class_name:"User"
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :entries,dependent: :destroy
  has_many :messages,dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites,dependent: :destroy
  has_many :books,dependent: :destroy
  has_many :book_comments,dependent: :destroy
  
  has_many :group_users,dependent: :destroy

  has_many :entries,dependent: :destroy
  has_many :messages,dependent: :destroy

  has_many :read_counts,dependent: :destroy

  has_many :relationships,class_name:"Relationship",foreign_key:"follower_id",dependent: :destroy
  has_many :reverse_of_relationships,class_name:"Relationship",foreign_key:"followed_id",dependent: :destroy
  has_many :followings,through: :relationships,source: :followed
  has_many :followers,through: :reverse_of_relationships,source: :follower

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length: {maximum: 50}


  def follow(user_id)
  relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def get_profile_image
    if profile_image.attached?
    profile_image
    else
      'no_image.jpg'
    end
  end

  def self.looks(search,word)
    if search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
      elsif search == "backward_match"
        @user = User.where("name LIKE?","%#{word}")
        elsif search == "partial_match"
          @user = User.where("name LIKE?","%#{word}%")
        else
          @user = User.all
        end
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logined_user
  before_action :ensure_correct_user, only: [:edit,:update]
   before_action :authenticate_user!, only: [:show]

  def show
   @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
    @book = Book.new
    @books = @user.books
end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update

    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else

      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

   def logined_user
    unless user_signed_in?
      redirect_to new_user_session_path
  end
end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td>
          <% unless current_user.id == user.id %>
          <% if current_user.following?(user) %>

          <%= link_to "フォロー外す",user_relationships_path(user.id),method: :delete,class: "mb-3 btn btn-danger" %>
          <% else %>
          <%= link_to "フォローする",user_relationships_path(user.id),method: :post,class: "mb-3 btn btn-success" %>
          <% end %>
          <% end %>

        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <td>follows</td>
    <td><%= link_to user_followings_path(user.id) do %>
    <%= user.followings.count %>
    <% end %>
    </td>
  </tr>
  <tr>
    <td>followers</td>
    <td>
      <%= link_to user_followers_path(user.id) do %>
      <%= user.followers.count %>
      <% end %>
      </td>
  </tr>
</table>
 <% unless current_user.id == user.id %>
          <% if current_user.following?(user) %>

          <%= link_to "フォロー外す",user_relationships_path(user.id),method: :delete,class: "mb-3 btn btn-danger" %>
          <% else %>
          <%= link_to "フォローする",user_relationships_path(user.id),method: :post,class: "mb-3 btn btn-success" %>
          <% end %>
          <% end %>



<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
  <%= render "books/search" %>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
     <%= render 'layouts/errors', obj: @user %>
    <%= form_with model:@user, local:true do |f| %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
  <%= render "books/search" %>
  <div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <%= link_to "グループを作成する",new_group_path %> |
  <%= link_to "グループ一覧",groups_path %>
</div>
</div>
</div>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
<h2>User info</h2>
<%= render 'info', user: current_user %>

<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>
</div>
 <div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<%= render 'index',users: @users %>
</div>

  </div>
</div>

app/views/users/show.html.erb
  <%= render "books/search" %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>

      <% unless @user.id == current_user.id %>
      <% if (current_user.following? @user) && (@user.following? current_user) %>
      <% if @isRoom == true %>
      <p class="user-show-room"><a href = "/rooms/<%= @roomId %>" class = "btn btn-primary btn-lg">チャットへ</a></p>
      <% else %>
      <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
      <%= e.hidden_field :user_id,value: @user.id %>
      <% end %>
      <%= f.submit "チャットを始める",class: "btn btn-primary btn-lg" %>
      <% end %>
      <% end %>
      <% end %>
      <% end %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>